server {
    listen 3000;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Сжатие для оптимизации
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        try_files $uri $uri/ /index.html;
    }
    # TODO: Пересмотреть подумать если есть возможность
    # Ошибки 404 перенаправляем на index.html (дополнительная страховка)
    error_page 404 /index.html;
}
