# Так чтобы заработало на серваке создать папку, туда docker-compose.yml с .env, Caddyfile и мб еще чтото
services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 5s
      retries: 5
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    container_name: caddy
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
  go:
    image: ghcr.io/artemchadaev/auc-go:v0.1
    environment:
      - DEPLOY=true
    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8080:8080"
  react:
    image: ghcr.io/artemchadaev/auc-react:v0.1
    ports:
      - "3000:3000"